### ISSUE TITLE
插件修改小建议

### ISSUE THREAD

**Issue by zsxsoft** [tangkunyin/codecompressforzblog#1]
为了预防插件类、函数、变量命名导致冲突问题，我们建议每一个应用开发者在include.php内定义的名字都带有插件名作为前缀，如

``` php
function CodeCompress_Begin() { 
}
```

HtmlMinify类在全局include，所以建议把那个的类名也修改下~

**Comment by tangkunyin** [comment]
这个问题已经改正，多谢支持
